### PR TITLE
Clicklin patch 5

### PR DESCRIPTION
**Pull request by clicklin**

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Hi @clicklin,

Your PR seems to be a duplicate of #18. Can you please update this PR to show only the changes made between the previous one and today ?

**Comment by clicklin** [comment]
Hi @Quetzacoalt91,

I don't remember change file views/templates/hook/admin_order.tpl

How can I revert this file changes?

**Comment by Quetzacoalt91** [comment]
Hi @clicklin,

This gonna be difficult because the commits have the same content, but not the same hash. Git cannot know that they are the same.
I advice you to create a new PR with only the new changes. Because I wont be able to remove the commits duplicated.

**Comment by jaume-solis** [comment]
Hi @Quetzacoalt91 

We don't see your response, sorry about that.

Where we create new PR on master on a new branch?

**Comment by Quetzacoalt91** [comment]
Hi @clicklin,

I took the only commit not found on the main repository. It is available here: https://github.com/PrestaShop/clickline/commit/5d9b5793e76f5654f767a2a8ab874564a9b2622c

On your side, please synchronise your fork with the main repository. I close this PR because it has been merged manually.

Best regards

**Pull request closed without merging**
